# Generated by Django 2.2.3 on 2019-09-15 19:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mantis',
            fields=[
                ('name', models.CharField(help_text='Should be <StickerName>_<StickerGeneration> ie:Alien_G1', max_length=200, primary_key=True, serialize=False)),
                ('birthday', models.DateField(default=datetime.date.today, help_text='Should be the date of hatching.')),
                ('deathday', models.DateField(blank=True, default=datetime.date.today, help_text='In the case of death.')),
                ('cause_of_death', models.CharField(default='Old age', help_text='Can be Mismolt, Old age or whatever caused it.', max_length=200)),
                ('nickname', models.CharField(blank=True, default=models.CharField(help_text='Should be <StickerName>_<StickerGeneration> ie:Alien_G1', max_length=200, primary_key=True, serialize=False), max_length=200)),
                ('lifestage', models.IntegerField(default=1, help_text='The current L# of the bug.')),
                ('had_fall', models.BooleanField(default=False)),
                ('not_eatting', models.BooleanField(default=False)),
                ('mated', models.BooleanField(default=False)),
                ('died_unknown', models.BooleanField(default=False, help_text='Did the bug bite it mysteriously?')),
                ('died_natural', models.BooleanField(default=False, help_text='Did they live a long and happy life?')),
                ('generation', models.IntegerField(default=0, help_text='Is this the offspring of one of ours, how many generations in?')),
                ('sticker_generation', models.IntegerField(default=0, help_text='How many have championed this sticker before?')),
                ('gender', models.CharField(default='Unsexed', help_text='Does the bug have wedding tackle?', max_length=12)),
                ('personality', models.CharField(default="I'm a standard ass bug. Can't fault me for meeting expectations.", help_text="What's the bug like? Outgoing? Skittish?", max_length=1200)),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('image', models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/')),
                ('mantis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantis_profiles.Mantis')),
            ],
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, help_text='What day IS it though?')),
                ('molted', models.BooleanField(default=False, help_text='Has the bug molted today?')),
                ('notes', models.CharField(default='Nothing in particular', help_text='Anything odd or interesting to report today?', max_length=1200)),
                ('fed_today', models.BooleanField(default=False)),
                ('personality_changes', models.CharField(default='None.', help_text='Any notable shifts in personality?', max_length=240)),
                ('mated', models.BooleanField(default=False, help_text='Have they done the horizontal monster mash today?')),
                ('crisis_today', models.BooleanField(default=False, help_text='Did something stupid happen?')),
                ('amount_fed', models.CharField(default='None.', help_text='How much of what did they eat? Ex: Big Piece of Mealworm, Whole housefly, 3 Neighbor kids', max_length=200)),
                ('high_temp_last_24', models.IntegerField(default=0, help_text='How high was it? Jake will do this later.')),
                ('low_temp_last_24', models.IntegerField(default=0, help_text='Also will be a Jake job later.')),
                ('ooths_produced', models.BooleanField(default=False, help_text='Is this bug a mammy bug?')),
                ('mantis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantis_profiles.Mantis')),
            ],
        ),
    ]
