# Generated by Django 2.2.5 on 2019-09-15 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantis_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(default='/pic_folder/None/None_<built-in method today of type object at 0x3ad7a8>.png', upload_to='pic_folder/'),
        ),
    ]
