# Generated by Django 2.2.5 on 2019-09-16 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantis_profiles', '0002_auto_20190915_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantis',
            name='color',
            field=models.CharField(default='Uncertain', help_text="Ex. Brown, Green, Half Brown Half Green, Covered in the blood of it's enemies", max_length=120),
        ),
    ]
