# Generated by Django 2.2.5 on 2019-09-16 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantis_profiles', '0003_mantis_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantis',
            name='species',
            field=models.CharField(default='Tenodora Sinensis', help_text='Species, I.E: Tenodora Sinenses, Idolomantis Diabolica, Steve', max_length=120),
        ),
    ]
