# Generated by Django 2.2.5 on 2019-09-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantis_profiles', '0004_mantis_species'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantis',
            name='profile_pic',
            field=models.CharField(default='/static/mantis_riding_snake1.jpg', help_text='Is changed every new picture, can be set manually if need be from /static/', max_length=260),
        ),
    ]
