# Generated by Django 2.2.5 on 2019-09-19 14:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantis_profiles', '0005_mantis_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Environment_Log',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('notes', models.CharField(default='None', max_length=240)),
                ('humidity', models.CharField(default='0', max_length=4)),
                ('temp', models.CharField(default='0', max_length=3)),
            ],
        ),
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(upload_to='static/uploaded_pics'),
        ),
    ]
