# Generated by Django 2.2.5 on 2019-09-19 15:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mantis_profiles', '0006_auto_20190919_0913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feeder_Culture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('culture_name', models.CharField(default='Name Me', help_text='Sticker on the culture', max_length=50)),
                ('aprox_population', models.CharField(default='100', help_text='Estimated numbers', max_length=50)),
                ('culture_type', models.CharField(default='Mealworm', help_text="What's in it?", max_length=120)),
                ('culture_bedding', models.CharField(default='Oatato', help_text='What are they in?', max_length=120)),
                ('culture_watering', models.CharField(default='Beetle Jelly', help_text='What are they getting their water from?', max_length=120)),
                ('culture_notes', models.CharField(default='None', help_text='Notes about the overall culture', max_length=360)),
                ('culture_creation_date', models.DateField(default=datetime.date.today, help_text='When was this culture created?')),
                ('culture_retired', models.BooleanField(default=False, help_text='Has it been retired or the feeders removed or died?')),
            ],
        ),
        migrations.CreateModel(
            name='Feeder_Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('log_notes', models.CharField(default='None', help_text='Anything to note.', max_length=1200)),
                ('changed_watering_media', models.BooleanField(default=False)),
                ('cleaned_culture_tank', models.BooleanField(default=False)),
                ('culture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantis_profiles.Feeder_Culture')),
            ],
        ),
    ]
