# Generated by Django 2.2.5 on 2020-07-03 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantis_profiles', '0008_gecko_gecko_log_gecko_morph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gecko',
            name='nickname',
            field=models.CharField(blank=True, default='None', max_length=200),
        ),
    ]
