# Generated by Django 3.1 on 2020-10-01 16:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mantis_profiles', '0010_auto_20200703_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('culture_name', models.CharField(default='Name Me', help_text='Sticker on the culture', max_length=50)),
                ('aprox_population', models.CharField(default='100', help_text='Estimated numbers', max_length=50)),
                ('culture_type', models.CharField(default='Mealworm', help_text="What's in it?", max_length=120)),
                ('culture_bedding', models.CharField(default='Oatato', help_text='What are they in?', max_length=120)),
                ('culture_watering', models.CharField(default='Beetle Jelly', help_text='What are they getting their water from?', max_length=120)),
                ('culture_notes', models.CharField(default='None', help_text='Notes about the overall culture', max_length=360)),
                ('culture_creation_date', models.DateField(default=datetime.date.today, help_text='When was this culture created?')),
                ('culture_retired', models.BooleanField(default=False, help_text='Has it been retired or the feeders removed or died?')),
                ('had_mass_dieoff', models.BooleanField(default=False, help_text='Has this culture ever suffered a mass dieoff?')),
                ('quarantined', models.BooleanField(default=False, help_text='Is this culture quarantined from other cultures for some reason?')),
                ('quarantine_reasons', models.CharField(default='None', help_text='CSV: Mites, Unknown Worms, Recent Mass Death of Unknown Cause, etc', max_length=400)),
                ('parent_culture', models.CharField(default='None', help_text='TROGDORRRRRRRRRRR wants to know what culture begat this one.', max_length=120)),
                ('culture_health', models.CharField(default='Good', help_text='Good, Poor, Unknown, Destroyed, Collapsed (This will be a drop-down when I write the forms.)', max_length=120)),
                ('gut_loading', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Culture_Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('log_notes', models.CharField(default='None', help_text='Anything to note.', max_length=1200)),
                ('changed_watering_media', models.BooleanField(default=False)),
                ('complete_food_change', models.BooleanField(default=False, help_text='Dumped out the old food, put in fresh.')),
                ('added_fresh_food', models.BooleanField(default=False, help_text='Added food to old food.')),
                ('food_added', models.CharField(default='None', help_text="Eg; Fluker's Cricket Diet, Orange Cubes, etc", max_length=200)),
                ('cleaned_culture_tank', models.BooleanField(default=False)),
                ('mite_infestation', models.BooleanField(default=False)),
                ('mass_death', models.BooleanField(default=False)),
                ('quarantined', models.BooleanField(default=False)),
                ('reason_for_quarantine', models.CharField(default='None', help_text='Mites, Mold, etc. I need to make this a drop down too.', max_length=500)),
                ('recent_spawning_activity', models.BooleanField(default=False, help_text='Fresh eggs, ooths, evidence of them doing the horizontal monster mash?')),
                ('high_temp_last_24', models.IntegerField(default=0, help_text='You could use the logging endpoints or manually input the temp. Code assumes F, will change if needed.')),
                ('low_temp_last_24', models.IntegerField(default=0, help_text='You could use the logging endpoints or manually input the temp. Fahrenheit. ^ ')),
                ('culture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantis_profiles.culture')),
            ],
        ),
        migrations.CreateModel(
            name='Gecko_Egg_Clutch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_produced', models.DateTimeField(auto_now=True)),
                ('eggs', models.IntegerField()),
                ('slugs', models.IntegerField()),
                ('notes', models.CharField(max_length=255)),
                ('father', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gecko_father', to='mantis_profiles.gecko')),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gecko_mother', to='mantis_profiles.gecko')),
            ],
        ),
        migrations.CreateModel(
            name='Mantis_Ooth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_produced', models.DateTimeField(auto_now=True)),
                ('notes', models.CharField(max_length=255)),
                ('father', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantis_father', to='mantis_profiles.mantis')),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantis_mother', to='mantis_profiles.mantis')),
            ],
        ),
        migrations.RemoveField(
            model_name='feeder_log',
            name='culture',
        ),
        migrations.AddField(
            model_name='environment_log',
            name='location',
            field=models.CharField(default='Unspecified', max_length=50),
        ),
        migrations.AddField(
            model_name='gecko_log',
            name='cleaned_food_bowl',
            field=models.BooleanField(default=False, help_text='Have to clean the food bowl?'),
        ),
        migrations.AddField(
            model_name='gecko_log',
            name='cleaned_water_bowl',
            field=models.BooleanField(default=False, help_text='Have to clean the water bowl?'),
        ),
        migrations.AddField(
            model_name='gecko_log',
            name='habitat_full_clean',
            field=models.BooleanField(default=False, help_text='Did the habitat get cleaned today?'),
        ),
        migrations.AddField(
            model_name='gecko_log',
            name='moist_hide_media_changed',
            field=models.BooleanField(default=False, help_text='Changed out stanky moss?'),
        ),
        migrations.AddField(
            model_name='gecko_log',
            name='moisturized_moist_hide',
            field=models.BooleanField(default=False, help_text='Spritz the moss?'),
        ),
        migrations.AddField(
            model_name='gecko_log',
            name='water_bowl_good',
            field=models.BooleanField(default=False, help_text='Enough water in the water bowl?'),
        ),
        migrations.DeleteModel(
            name='Feeder_Culture',
        ),
        migrations.DeleteModel(
            name='Feeder_Log',
        ),
    ]
