# Generated by Django 2.2.5 on 2020-07-03 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantis_profiles', '0010_auto_20200703_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='gecko_log',
            name='cleaned_food_bowl',
            field=models.BooleanField(default=False, help_text='Have to clean the food bowl?'),
        ),
        migrations.AddField(
            model_name='gecko_log',
            name='cleaned_water_bowl',
            field=models.BooleanField(default=False, help_text='Have to clean the water bowl?'),
        ),
        migrations.AddField(
            model_name='gecko_log',
            name='habitat_full_clean',
            field=models.BooleanField(default=False, help_text='Did the habitat get cleaned today?'),
        ),
        migrations.AddField(
            model_name='gecko_log',
            name='moist_hide_media_changed',
            field=models.BooleanField(default=False, help_text='Changed out stanky moss?'),
        ),
        migrations.AddField(
            model_name='gecko_log',
            name='moisturized_moist_hide',
            field=models.BooleanField(default=False, help_text='Spritz the moss?'),
        ),
        migrations.AddField(
            model_name='gecko_log',
            name='water_bowl_good',
            field=models.BooleanField(default=False, help_text='Enough water in the water bowl?'),
        ),
    ]
