# Generated by Django 2.2.5 on 2020-07-04 15:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mantis_profiles', '0011_auto_20200703_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('culture_name', models.CharField(default='Name Me', help_text='Sticker on the culture', max_length=50)),
                ('aprox_population', models.CharField(default='100', help_text='Estimated numbers', max_length=50)),
                ('culture_type', models.CharField(default='Mealworm', help_text="What's in it?", max_length=120)),
                ('culture_bedding', models.CharField(default='Oatato', help_text='What are they in?', max_length=120)),
                ('culture_watering', models.CharField(default='Beetle Jelly', help_text='What are they getting their water from?', max_length=120)),
                ('culture_notes', models.CharField(default='None', help_text='Notes about the overall culture', max_length=360)),
                ('culture_creation_date', models.DateField(default=datetime.date.today, help_text='When was this culture created?')),
                ('culture_retired', models.BooleanField(default=False, help_text='Has it been retired or the feeders removed or died?')),
                ('had_mass_dieoff', models.BooleanField(default=False, help_text='Has this culture ever suffered a mass dieoff?')),
                ('quarantined', models.BooleanField(default=False, help_text='Is this culture quarantined from other cultures for some reason?')),
                ('quarantine_reasons', models.CharField(default='None', help_text='CSV: Mites, Unknown Worms, Recent Mass Death of Unknown Cause, etc', max_length=400)),
                ('parent_culture', models.CharField(default='None', help_text='TROGDORRRRRRRRRRR wants to know what culture begat this one.', max_length=120)),
                ('culture_health', models.CharField(default='Good', help_text='Good, Poor, Unknown, Destroyed, Collapsed (This will be a drop-down when I write the forms.)', max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Culture_Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('log_notes', models.CharField(default='None', help_text='Anything to note.', max_length=1200)),
                ('changed_watering_media', models.BooleanField(default=False)),
                ('cleaned_culture_tank', models.BooleanField(default=False)),
                ('mite_infestation', models.BooleanField(default=False)),
                ('mass_death', models.BooleanField(default=False)),
                ('quarantined', models.BooleanField(default=False)),
                ('reason_for_quarantine', models.CharField(default='None', help_text='Mites, Mold, etc. I need to make this a drop down too.', max_length=500)),
                ('recent_spawning_activity', models.BooleanField(default=False, help_text='Fresh eggs, ooths, evidence of them doing the horizontal monster mash?')),
                ('high_temp_last_24', models.IntegerField(default=0, help_text='You could use the logging endpoints or manually input the temp. Code assumes F, will change if needed.')),
                ('low_temp_last_24', models.IntegerField(default=0, help_text='You could use the logging endpoints or manually input the temp. Fahrenheit. ^ ')),
                ('culture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantis_profiles.Culture')),
            ],
        ),
        migrations.RemoveField(
            model_name='feeder_log',
            name='culture',
        ),
        migrations.DeleteModel(
            name='Feeder_Culture',
        ),
        migrations.DeleteModel(
            name='Feeder_Log',
        ),
    ]
