# Generated by Django 2.2.5 on 2020-07-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantis_profiles', '0012_auto_20200704_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='culture_log',
            name='added_fresh_food',
            field=models.BooleanField(default=False, help_text='Added food to old food.'),
        ),
        migrations.AddField(
            model_name='culture_log',
            name='complete_food_change',
            field=models.BooleanField(default=False, help_text='Dumped out the old food, put in fresh.'),
        ),
        migrations.AddField(
            model_name='culture_log',
            name='food_added',
            field=models.CharField(default='None', help_text="Eg; Fluker's Cricket Diet, Orange Cubes, etc", max_length=200),
        ),
    ]
