# Generated by Django 3.1 on 2020-10-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantis_profiles', '0013_auto_20201001_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('size', models.CharField(help_text='50oz, 10ft, 24in x 52in, etc.', max_length=240)),
                ('stock', models.IntegerField(help_text='How many are in inventory?')),
                ('links', models.JSONField(default=list)),
                ('historical_price_data', models.JSONField(default=list)),
                ('brand', models.CharField(help_text="Fluker's, ZooMed, Etc.", max_length=255)),
            ],
        ),
    ]
