# Generated by Django 2.2.5 on 2020-07-29 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mantis_profiles', '0013_auto_20200704_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mantis_Ooth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_produced', models.DateTimeField(auto_now=True)),
                ('notes', models.CharField(max_length=255)),
                ('father', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantis_father', to='mantis_profiles.Mantis')),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantis_mother', to='mantis_profiles.Mantis')),
            ],
        ),
        migrations.CreateModel(
            name='Gecko_Egg_Clutch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_produced', models.DateTimeField(auto_now=True)),
                ('eggs', models.IntegerField()),
                ('slugs', models.IntegerField()),
                ('notes', models.CharField(max_length=255)),
                ('father', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gecko_father', to='mantis_profiles.Gecko')),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gecko_mother', to='mantis_profiles.Gecko')),
            ],
        ),
    ]
