# Generated by Django 3.1 on 2020-10-06 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mantis_profiles', '0014_inventory_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items_purchased', models.JSONField(default=list, help_text='Items in list structure.')),
                ('purchased_from', models.CharField(default='Amazon', help_text='Where this purchase was made.', max_length=200)),
                ('transaction_id', models.CharField(default='None', max_length=200)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, help_text='Total amount paid, eg; 54.32', max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory_Consumption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_size', models.CharField(default='6oz', max_length=200)),
                ('went_bad', models.BooleanField(default=False, help_text='Did it rot, or break prematurely?')),
                ('consumed_naturally', models.BooleanField(default=True, help_text='Did it just run out or expire as expected?')),
                ('item_consumed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantis_profiles.inventory_item')),
            ],
        ),
    ]
