# Generated by Django 2.2.5 on 2020-07-30 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantis_profiles', '0014_gecko_egg_clutch_mantis_ooth'),
    ]

    operations = [
        migrations.AddField(
            model_name='culture',
            name='gut_loading',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='environment_log',
            name='location',
            field=models.CharField(default='Unspecified', max_length=50),
        ),
    ]
