# Generated by Django 3.1 on 2020-10-13 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantis_profiles', '0016_gecko_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='gecko_log',
            name='has_defecated',
            field=models.BooleanField(default=False, help_text='Did the gecko drop a deuce?'),
        ),
    ]
