# Generated by Django 3.1 on 2020-10-15 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culture',
            name='notes',
            field=models.TextField(blank=True, default='', max_length=25000),
        ),
        migrations.AlterField(
            model_name='culture',
            name='parent_culture',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='culture.culture'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='notes',
            field=models.TextField(blank=True, default='', max_length=25000),
        ),
        migrations.AlterField(
            model_name='feed',
            name='recipe',
            field=models.TextField(blank=True, default='', help_text='If you have a recipe with ratios you can put it here.', max_length=250000),
        ),
        migrations.AlterField(
            model_name='log',
            name='notes',
            field=models.TextField(blank=True, default='', max_length=25000),
        ),
        migrations.AlterField(
            model_name='specie',
            name='notes',
            field=models.TextField(blank=True, default='', max_length=25000),
        ),
    ]
