# Generated by Django 3.1 on 2020-10-15 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0004_auto_20201015_1221'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'get_latest_by': 'date', 'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='quarantine',
            options={'get_latest_by': 'start_date', 'ordering': ['start_date']},
        ),
    ]
