# Generated by Django 3.1 on 2020-10-27 12:03

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(default='', max_length=240)),
                ('species', models.CharField(default='', max_length=240)),
                ('species_synonyms', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=240), blank=True, default='', size=None)),
                ('domain', models.CharField(default='', max_length=240)),
                ('phylum', models.CharField(default='', max_length=240)),
                ('specie_class', models.CharField(default='', max_length=240)),
                ('order', models.CharField(default='', max_length=240)),
                ('family', models.CharField(default='', max_length=240)),
                ('genus', models.CharField(default='', max_length=240)),
                ('discoverer', models.CharField(default='', max_length=240)),
                ('discovery_date', models.DateField(default=datetime.date.today)),
                ('lifespan', models.CharField(default='', max_length=240)),
                ('interesting_facts', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=2048), blank=True, default='', help_text='Separated by comas', size=None)),
                ('natural_habitat', models.CharField(default='', max_length=240)),
                ('temperature_range', models.CharField(default='', max_length=240)),
                ('humidity_range', models.CharField(default='', max_length=240)),
                ('diet', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=240), default='', help_text='Coma separated list.', size=None)),
                ('behaviour', models.TextField(default='', max_length=3240)),
                ('tsd', models.BooleanField(default=False, help_text='Temperature-dependant Sex Determination')),
                ('breeding_info', models.TextField(default='', max_length=5000)),
                ('active_breeding_time', models.CharField(default='', help_text='eg; June, Summer, or Summer and Fall', max_length=240)),
                ('average_yearly_offspring', models.IntegerField(default=0)),
                ('habitat_requirements', models.TextField(default='', max_length=5000)),
                ('other_information', models.TextField(default='', max_length=12000)),
                ('picture', models.ImageField(default='nope.jpeg', upload_to='meta_pictures/')),
            ],
        ),
    ]
