# Generated by Django 3.1 on 2020-10-27 12:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specie_meta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specie',
            name='diet',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=240), default=list, help_text='Coma separated list.', size=None),
        ),
        migrations.AlterField(
            model_name='specie',
            name='interesting_facts',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=2048), blank=True, default=list, help_text='Separated by comas', size=None),
        ),
        migrations.AlterField(
            model_name='specie',
            name='species_synonyms',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=240), blank=True, default=list, size=None),
        ),
    ]
