# Generated by Django 3.1 on 2020-10-29 18:53

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=120)),
                ('brand', models.CharField(default='', max_length=120)),
                ('price', models.FloatField(default=0.0)),
                ('description', models.TextField(default='', max_length=1200)),
                ('upc', models.ImageField(blank=True, null=True, upload_to='upcs/')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='item_pics/')),
                ('item_type', models.CharField(choices=[('Feed', 'Feed'), ('Watering Media', 'Watering Media'), ('Substrate', 'Substrate'), ('Habitat Item', 'Habitat Item'), ('Heat Pad/Wire', 'Heat Pad/Wire'), ('Habitat Tank', 'Habitat Tank'), ('Cleaning Product', 'Cleaning Product'), ('Incubator', 'Incubator'), ('Tool', 'Tool'), ('Dietary Supplement', 'Dietary Supplement'), ('Other', 'Other')], default='Other', max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='inventory.item')),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_id', models.CharField(default='', max_length=120)),
                ('total_cost', models.FloatField(default=0.0)),
                ('ordered_from', models.CharField(default='', max_length=120)),
                ('order_date', models.DateField(default=datetime.date.today)),
                ('items', models.ManyToManyField(to='inventory.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Item_Expiration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expiration_date', models.DateField(default=datetime.date.today)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
            ],
        ),
        migrations.CreateModel(
            name='Item_Consumption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_consumed', models.DateField(default=datetime.date.today)),
                ('expired', models.BooleanField(default=False)),
                ('notes', models.TextField(default='', max_length=1200)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
            ],
        ),
    ]
