# Generated by Django 3.1.2 on 2020-10-20 19:33

import datetime
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Breeding_Log',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
                ('successful', models.BooleanField(default=False)),
                ('notes', models.TextField(max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='Clutch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
                ('breeding_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leopard_gecko.breeding_log')),
            ],
        ),
        migrations.CreateModel(
            name='Egg',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weight', models.FloatField(help_text='grams')),
                ('size', models.FloatField(help_text='cm')),
                ('name', models.CharField(max_length=120)),
                ('appears_healthy', models.BooleanField(default=False)),
                ('clutch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leopard_gecko.clutch')),
            ],
        ),
        migrations.CreateModel(
            name='Gecko',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Anonygex', max_length=120)),
                ('nickname', models.CharField(blank=True, max_length=120)),
                ('birth_date', models.DateField(default=datetime.date.today)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unsexed')], default='U', max_length=60)),
                ('personality', models.CharField(blank=True, max_length=240)),
                ('profile_picture', models.ImageField(default='nope.jpeg', upload_to='leo_prof_pics/')),
                ('bio', models.TextField(blank=True, max_length=8096)),
                ('caretaker_notes', models.TextField(blank=True, max_length=8096)),
                ('caretaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('egg', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='leopard_gecko.egg')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
                ('defecation', models.BooleanField(default=False)),
                ('behavior', models.TextField(blank=True, max_length=2048)),
                ('problems', models.TextField(blank=True, max_length=2048)),
                ('other_notes', models.TextField(blank=True, max_length=2048)),
                ('gecko', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leopard_gecko.gecko')),
            ],
        ),
        migrations.CreateModel(
            name='Morph',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('morph_name', models.CharField(max_length=120)),
                ('morph_type', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('COLOR', 'Color'), ('PATTERN', 'Pattern'), ('EYE', 'Eye'), ('SIZE', 'Size')], default='COLOR', max_length=16), size=None)),
                ('color', models.CharField(blank=True, max_length=24)),
                ('discovery_date', models.DateField(blank=True)),
                ('picture', models.ImageField(default='nope.jpeg', upload_to='leo_morph_pics/')),
                ('description', models.TextField(blank=True, max_length=1024)),
                ('is_dangerous', models.BooleanField(default=False)),
                ('polygenic', models.BooleanField(default=False)),
                ('dominant', models.BooleanField(default=False)),
                ('codominant', models.BooleanField(default=False)),
                ('incomplete_dominant', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tank_Object',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_added', models.DateField(default=datetime.date.today)),
                ('name', models.CharField(max_length=240)),
                ('purpose', models.CharField(max_length=240)),
                ('retired', models.BooleanField(default=False)),
                ('picture', models.ImageField(blank=True, upload_to='leo_molt_pics/')),
                ('notes', models.TextField(blank=True, max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creation_date', models.DateField(default=datetime.date.today)),
                ('contents', models.ManyToManyField(to='leopard_gecko.Tank_Object')),
                ('gecko', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leopard_gecko.gecko')),
            ],
        ),
        migrations.CreateModel(
            name='Molt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
                ('after_molt_picture', models.ImageField(blank=True, upload_to='leo_molt_pics/')),
                ('problems_with_molt', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, max_length=2048)),
                ('gecko', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leopard_gecko.gecko')),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leopard_gecko.log')),
            ],
        ),
        migrations.AddField(
            model_name='gecko',
            name='morphs',
            field=models.ManyToManyField(blank=True, to='leopard_gecko.Morph'),
        ),
        migrations.CreateModel(
            name='Feeding_Log',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
                ('feed', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=80), size=None)),
                ('feed_supplement', models.CharField(choices=[('CALC', 'Calcium'), ('VITD', 'Vitamin D & Calcium'), ('MULT', 'Multivitamin')], default='CALC', max_length=40)),
                ('notes', models.TextField(blank=True, max_length=2048)),
                ('gecko', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leopard_gecko.gecko')),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leopard_gecko.log')),
            ],
        ),
        migrations.CreateModel(
            name='Death',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
                ('reason', models.TextField(blank=True, max_length=2048)),
                ('gecko', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leopard_gecko.gecko')),
            ],
        ),
        migrations.CreateModel(
            name='Cleaning_Log',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('full_clean', models.BooleanField(default=False)),
                ('cleaner_used', models.CharField(max_length=120)),
                ('items_cleaned', models.CharField(blank=True, max_length=1024)),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leopard_gecko.tank')),
            ],
        ),
        migrations.AddField(
            model_name='breeding_log',
            name='father',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='father', to='leopard_gecko.gecko'),
        ),
        migrations.AddField(
            model_name='breeding_log',
            name='mother',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='mother', to='leopard_gecko.gecko'),
        ),
    ]
