# Generated by Django 3.1.2 on 2020-10-20 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leopard_gecko', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='morph',
            name='secondary_morph_type',
            field=models.CharField(choices=[('COLOR', 'Color'), ('PATTERN', 'Pattern'), ('EYE', 'Eye'), ('SIZE', 'Size'), ('NONE', 'None')], default='NONE', max_length=16),
        ),
        migrations.AlterField(
            model_name='gecko',
            name='egg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leopard_gecko.egg'),
        ),
        migrations.AlterField(
            model_name='gecko',
            name='morphs',
            field=models.ManyToManyField(blank=True, null=True, to='leopard_gecko.Morph'),
        ),
        migrations.AlterField(
            model_name='gecko',
            name='nickname',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='morph',
            name='discovery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='morph',
            name='morph_type',
            field=models.CharField(choices=[('COLOR', 'Color'), ('PATTERN', 'Pattern'), ('EYE', 'Eye'), ('SIZE', 'Size'), ('NONE', 'None')], default='COLOR', max_length=16),
        ),
    ]
