# Generated by Django 3.1.2 on 2020-10-20 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leopard_gecko', '0002_auto_20201020_1600'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cleaning_Log',
            new_name='Tank_Cleaning_Log',
        ),
    ]
