# Generated by Django 3.1.2 on 2020-10-20 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leopard_gecko', '0003_auto_20201020_1635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tank_cleaning_log',
            old_name='full_clean',
            new_name='full_tank_clean',
        ),
    ]
