# Generated by Django 3.1.2 on 2020-10-20 23:10

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('leopard_gecko', '0004_auto_20201020_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temperatures',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.date.today)),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leopard_gecko.tank')),
            ],
        ),
    ]
