# Generated by Django 3.1.2 on 2020-10-21 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leopard_gecko', '0005_temperatures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morph',
            name='color',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
