# Generated by Django 3.1.2 on 2020-10-27 00:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('leopard_gecko', '0007_auto_20201021_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='morph',
            name='tertiary_morph_type',
            field=models.CharField(choices=[('COLOR', 'Color'), ('PATTERN', 'Pattern'), ('EYE', 'Eye'), ('SIZE', 'Size'), ('NONE', 'None')], default='NONE', max_length=16),
        ),
        migrations.CreateModel(
            name='Morph_Combo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('eighth_req_morph', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eighthreqmorph', to='leopard_gecko.morph')),
                ('fifth_req_morph', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fifthreqmorph', to='leopard_gecko.morph')),
                ('first_req_morph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firstreqmorph', to='leopard_gecko.morph')),
                ('fourth_req_morph', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fourthreqmorph', to='leopard_gecko.morph')),
                ('morph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='morph', to='leopard_gecko.morph')),
                ('ninth_req_morph', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ninthreqmorph', to='leopard_gecko.morph')),
                ('second_req_morph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondreqmorph', to='leopard_gecko.morph')),
                ('seventh_req_morph', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seventhreqmorph', to='leopard_gecko.morph')),
                ('sixth_req_morph', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sixthreqmorph', to='leopard_gecko.morph')),
                ('tenth_req_morph', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenthreqmorph', to='leopard_gecko.morph')),
                ('third_req_morph', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thirdreqmorph', to='leopard_gecko.morph')),
            ],
        ),
    ]
