# Generated by Django 3.1.2 on 2020-10-27 00:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leopard_gecko', '0008_auto_20201026_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='morph',
            name='althernate_names',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=120), blank=True, null=True, size=None),
        ),
    ]
