# Generated by Django 3.1 on 2020-10-27 11:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leopard_gecko', '0010_auto_20201027_0503'),
    ]

    operations = [
        migrations.AddField(
            model_name='gecko',
            name='acquired_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='gecko',
            name='acquired_from',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AddField(
            model_name='gecko',
            name='acquired_price',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='gecko',
            name='breeder_email',
            field=models.EmailField(blank=True, default='admin@yarrbeard.com', max_length=254),
        ),
        migrations.AddField(
            model_name='gecko',
            name='breeder_name',
            field=models.CharField(default='Unknoown', max_length=120),
        ),
        migrations.AddField(
            model_name='gecko',
            name='captive_bred',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unknown', 'Unknown')], default='Unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='gecko',
            name='length',
            field=models.FloatField(default=0.0, help_text='In CM, unless you want to be obtuse.'),
        ),
        migrations.AddField(
            model_name='gecko',
            name='weight',
            field=models.FloatField(default=0.0, help_text='In grams, usually.'),
        ),
    ]
