# Generated by Django 3.1 on 2020-10-27 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leopard_gecko', '0011_auto_20201027_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gecko',
            name='breeder_name',
            field=models.CharField(default='Unknown', max_length=120),
        ),
    ]
