# Generated by Django 3.1 on 2020-11-24 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leopard_gecko', '0013_measurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='spent_time_in_enrichment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='log',
            name='time_spent_in_enrichment',
            field=models.IntegerField(default=0, help_text='In minutes'),
        ),
    ]
